import type { TemplateDefinition } from './types';

export const landscapeSplit: TemplateDefinition = {
  id: 'landscape-split',
  name: 'Overlay Announcement',
  category: 'announcement',
  thumbnail: '/templates/landscape-split-thumb.png',
  width: 1200,
  height: 628,
  format: 'landscape',
  defaults: {
    primaryColor: '#ffffff',
    secondaryColor: '#101322',
    accentColor: '#1235e2',
    fontFamily: 'Raleway',
  },
  layers: [
    {
      id: 'bg-image',
      type: 'image',
      x: 0,
      y: 0,
      width: 1200,
      height: 628,
      src: '',
      editable: true,
    },
    {
      id: 'overlay-panel',
      type: 'rect',
      x: 560,
      y: 0,
      width: 640,
      height: 628,
      fill: '#ffffff',
      opacity: 0.92,
      colorRole: 'primary',
    },
    {
      id: 'headline',
      type: 'text',
      x: 600,
      y: 140,
      width: 560,
      height: 120,
      text: 'Big Announcement',
      fontSize: 44,
      fontFamily: 'Raleway',
      fontStyle: 'bold',
      fill: '#101322',
      align: 'left',
      lineHeight: 1.2,
      role: 'headline',
      colorRole: 'secondary',
    },
    {
      id: 'body',
      type: 'text',
      x: 600,
      y: 280,
      width: 560,
      height: 100,
      text: 'We are excited to share something new with you. Stay tuned for details.',
      fontSize: 20,
      fontFamily: 'Raleway',
      fontStyle: 'normal',
      fill: '#6b7280',
      align: 'left',
      lineHeight: 1.5,
      role: 'body',
    },
    {
      id: 'cta-bg',
      type: 'rect',
      x: 600,
      y: 420,
      width: 200,
      height: 48,
      fill: '#1235e2',
      cornerRadius: 8,
      colorRole: 'accent',
    },
    {
      id: 'cta-text',
      type: 'text',
      x: 600,
      y: 420,
      width: 200,
      height: 48,
      text: 'Read More',
      fontSize: 18,
      fontFamily: 'Raleway',
      fontStyle: 'bold',
      fill: '#ffffff',
      align: 'center',
      padding: 13,
      role: 'cta',
    },
  ],
};
