import type { TemplateDefinition } from './types';

export const landscapeCta: TemplateDefinition = {
  id: 'landscape-cta',
  name: 'Split CTA',
  category: 'promo',
  thumbnail: '/templates/landscape-cta-thumb.png',
  width: 1200,
  height: 628,
  format: 'landscape',
  defaults: {
    primaryColor: '#1235e2',
    secondaryColor: '#ffffff',
    accentColor: '#f59e0b',
    fontFamily: 'Inter',
  },
  layers: [
    {
      id: 'left-bg',
      type: 'rect',
      x: 0,
      y: 0,
      width: 600,
      height: 628,
      fill: '#1235e2',
      colorRole: 'primary',
    },
    {
      id: 'right-image',
      type: 'image',
      x: 600,
      y: 0,
      width: 600,
      height: 628,
      src: '',
      editable: true,
    },
    {
      id: 'headline',
      type: 'text',
      x: 48,
      y: 120,
      width: 504,
      height: 140,
      text: 'Limited Time Offer',
      fontSize: 48,
      fontFamily: 'Inter',
      fontStyle: 'bold',
      fill: '#ffffff',
      align: 'left',
      lineHeight: 1.15,
      role: 'headline',
    },
    {
      id: 'body',
      type: 'text',
      x: 48,
      y: 280,
      width: 504,
      height: 80,
      text: 'Get the best deals on our top products before they are gone.',
      fontSize: 20,
      fontFamily: 'Inter',
      fontStyle: 'normal',
      fill: '#dbeafe',
      align: 'left',
      lineHeight: 1.5,
      role: 'body',
    },
    {
      id: 'cta-bg',
      type: 'rect',
      x: 48,
      y: 400,
      width: 220,
      height: 52,
      fill: '#f59e0b',
      cornerRadius: 10,
      colorRole: 'accent',
    },
    {
      id: 'cta-text',
      type: 'text',
      x: 48,
      y: 400,
      width: 220,
      height: 52,
      text: 'Learn More',
      fontSize: 20,
      fontFamily: 'Inter',
      fontStyle: 'bold',
      fill: '#1c1917',
      align: 'center',
      padding: 14,
      role: 'cta',
    },
  ],
};
