import type { TemplateDefinition } from './types';

export const portraitPromo: TemplateDefinition = {
  id: 'portrait-promo',
  name: 'Product Promo',
  category: 'promo',
  thumbnail: '/templates/portrait-promo-thumb.png',
  width: 1080,
  height: 1350,
  format: 'portrait',
  defaults: {
    primaryColor: '#7c3aed',
    secondaryColor: '#ffffff',
    accentColor: '#fbbf24',
    fontFamily: 'Poppins',
  },
  layers: [
    {
      id: 'product-image',
      type: 'image',
      x: 0,
      y: 0,
      width: 1080,
      height: 750,
      src: '',
      editable: true,
    },
    {
      id: 'bottom-bg',
      type: 'rect',
      x: 0,
      y: 750,
      width: 1080,
      height: 600,
      fill: '#7c3aed',
      colorRole: 'primary',
    },
    {
      id: 'headline',
      type: 'text',
      x: 60,
      y: 790,
      width: 960,
      height: 120,
      text: 'Spring Collection',
      fontSize: 52,
      fontFamily: 'Poppins',
      fontStyle: 'bold',
      fill: '#ffffff',
      align: 'left',
      lineHeight: 1.15,
      role: 'headline',
    },
    {
      id: 'body',
      type: 'text',
      x: 60,
      y: 930,
      width: 960,
      height: 80,
      text: 'Fresh styles for the new season. Free shipping on all orders.',
      fontSize: 24,
      fontFamily: 'Poppins',
      fontStyle: 'normal',
      fill: '#e9d5ff',
      align: 'left',
      lineHeight: 1.4,
      role: 'body',
    },
    {
      id: 'cta-bg',
      type: 'rect',
      x: 60,
      y: 1060,
      width: 260,
      height: 60,
      fill: '#fbbf24',
      cornerRadius: 14,
      colorRole: 'accent',
    },
    {
      id: 'cta-text',
      type: 'text',
      x: 60,
      y: 1060,
      width: 260,
      height: 60,
      text: 'Shop Now',
      fontSize: 22,
      fontFamily: 'Poppins',
      fontStyle: 'bold',
      fill: '#1c1917',
      align: 'center',
      padding: 17,
      role: 'cta',
    },
  ],
};
