import type { TemplateDefinition } from './types';

export const portraitElegant: TemplateDefinition = {
  id: 'portrait-elegant',
  name: 'Elegant Lifestyle',
  category: 'lifestyle',
  thumbnail: '/templates/portrait-elegant-thumb.png',
  width: 1080,
  height: 1350,
  format: 'portrait',
  defaults: {
    primaryColor: '#1c1917',
    secondaryColor: '#fafaf9',
    accentColor: '#d4a574',
    fontFamily: 'Playfair Display',
  },
  layers: [
    {
      id: 'bg-image',
      type: 'image',
      x: 0,
      y: 0,
      width: 1080,
      height: 1350,
      src: '',
      editable: true,
    },
    {
      id: 'border',
      type: 'rect',
      x: 40,
      y: 40,
      width: 1000,
      height: 1270,
      fill: '',
      opacity: 1,
      stroke: '#d4a574',
      strokeWidth: 2,
      colorRole: 'accent',
    },
    {
      id: 'center-overlay',
      type: 'rect',
      x: 140,
      y: 440,
      width: 800,
      height: 470,
      fill: '#1c1917',
      opacity: 0.75,
      colorRole: 'primary',
    },
    {
      id: 'headline',
      type: 'text',
      x: 180,
      y: 490,
      width: 720,
      height: 160,
      text: 'Timeless\nElegance',
      fontSize: 68,
      fontFamily: 'Playfair Display',
      fontStyle: 'normal',
      fill: '#fafaf9',
      align: 'center',
      lineHeight: 1.15,
      role: 'headline',
      colorRole: 'secondary',
    },
    {
      id: 'divider',
      type: 'rect',
      x: 460,
      y: 670,
      width: 160,
      height: 2,
      fill: '#d4a574',
      colorRole: 'accent',
    },
    {
      id: 'body',
      type: 'text',
      x: 200,
      y: 700,
      width: 680,
      height: 80,
      text: 'Curated pieces for the discerning individual.',
      fontSize: 22,
      fontFamily: 'Playfair Display',
      fontStyle: 'normal',
      fill: '#d6d3d1',
      align: 'center',
      lineHeight: 1.5,
      role: 'body',
    },
    {
      id: 'cta-text',
      type: 'text',
      x: 200,
      y: 810,
      width: 680,
      height: 50,
      text: 'Explore Collection',
      fontSize: 20,
      fontFamily: 'Playfair Display',
      fontStyle: 'normal',
      fill: '#d4a574',
      align: 'center',
      role: 'cta',
      colorRole: 'accent',
    },
  ],
};
