import type { TemplateDefinition } from './types';

export const squareHero: TemplateDefinition = {
  id: 'square-hero',
  name: 'Hero Product',
  category: 'product',
  thumbnail: '/templates/square-hero-thumb.png',
  width: 1080,
  height: 1080,
  format: 'square',
  defaults: {
    primaryColor: '#1235e2',
    secondaryColor: '#101322',
    accentColor: '#f59e0b',
    fontFamily: 'Inter',
  },
  layers: [
    {
      id: 'bg-image',
      type: 'image',
      x: 0,
      y: 0,
      width: 1080,
      height: 1080,
      src: '',
      editable: true,
    },
    {
      id: 'overlay',
      type: 'rect',
      x: 0,
      y: 680,
      width: 1080,
      height: 400,
      fill: '#101322',
      opacity: 0.85,
      colorRole: 'secondary',
    },
    {
      id: 'headline',
      type: 'text',
      x: 60,
      y: 710,
      width: 960,
      height: 120,
      text: 'Your Headline Here',
      fontSize: 56,
      fontFamily: 'Inter',
      fontStyle: 'bold',
      fill: '#ffffff',
      align: 'left',
      lineHeight: 1.2,
      role: 'headline',
    },
    {
      id: 'body',
      type: 'text',
      x: 60,
      y: 840,
      width: 960,
      height: 60,
      text: 'Add a short description of your product or offer.',
      fontSize: 24,
      fontFamily: 'Inter',
      fontStyle: 'normal',
      fill: '#d1d5db',
      align: 'left',
      lineHeight: 1.4,
      role: 'body',
    },
    {
      id: 'cta-bg',
      type: 'rect',
      x: 60,
      y: 930,
      width: 240,
      height: 56,
      fill: '#f59e0b',
      cornerRadius: 12,
      colorRole: 'accent',
    },
    {
      id: 'cta-text',
      type: 'text',
      x: 60,
      y: 930,
      width: 240,
      height: 56,
      text: 'Shop Now',
      fontSize: 22,
      fontFamily: 'Inter',
      fontStyle: 'bold',
      fill: '#101322',
      align: 'center',
      padding: 16,
      role: 'cta',
    },
  ],
};
