import type { TemplateDefinition } from './types';

export const squareMinimal: TemplateDefinition = {
  id: 'square-minimal',
  name: 'Minimal Lifestyle',
  category: 'lifestyle',
  thumbnail: '/templates/square-minimal-thumb.png',
  width: 1080,
  height: 1080,
  format: 'square',
  defaults: {
    primaryColor: '#f6f6f8',
    secondaryColor: '#101322',
    accentColor: '#1235e2',
    fontFamily: 'Poppins',
  },
  layers: [
    {
      id: 'bg-rect',
      type: 'rect',
      x: 0,
      y: 0,
      width: 1080,
      height: 1080,
      fill: '#f6f6f8',
      colorRole: 'primary',
    },
    {
      id: 'product-image',
      type: 'image',
      x: 90,
      y: 60,
      width: 900,
      height: 500,
      src: '',
      editable: true,
    },
    {
      id: 'headline',
      type: 'text',
      x: 90,
      y: 600,
      width: 900,
      height: 140,
      text: 'Clean & Simple',
      fontSize: 64,
      fontFamily: 'Poppins',
      fontStyle: 'bold',
      fill: '#101322',
      align: 'center',
      lineHeight: 1.1,
      role: 'headline',
      colorRole: 'secondary',
    },
    {
      id: 'body',
      type: 'text',
      x: 120,
      y: 760,
      width: 840,
      height: 80,
      text: 'A beautifully crafted product for your everyday life.',
      fontSize: 24,
      fontFamily: 'Poppins',
      fontStyle: 'normal',
      fill: '#6b7280',
      align: 'center',
      lineHeight: 1.5,
      role: 'body',
    },
    {
      id: 'cta-text',
      type: 'text',
      x: 90,
      y: 900,
      width: 900,
      height: 50,
      text: 'Discover More',
      fontSize: 22,
      fontFamily: 'Poppins',
      fontStyle: 'bold',
      fill: '#1235e2',
      align: 'center',
      role: 'cta',
      colorRole: 'accent',
    },
    {
      id: 'cta-underline',
      type: 'rect',
      x: 420,
      y: 952,
      width: 240,
      height: 3,
      fill: '#1235e2',
      colorRole: 'accent',
    },
  ],
};
