import type { TemplateDefinition } from './types';

export const storyProduct: TemplateDefinition = {
  id: 'story-product',
  name: 'Product Showcase',
  category: 'product',
  thumbnail: '/templates/story-product-thumb.png',
  width: 1080,
  height: 1920,
  format: 'story',
  defaults: {
    primaryColor: '#1235e2',
    secondaryColor: '#ffffff',
    accentColor: '#10b981',
    fontFamily: 'Montserrat',
  },
  layers: [
    {
      id: 'bg-image',
      type: 'image',
      x: 0,
      y: 0,
      width: 1080,
      height: 1920,
      src: '',
      editable: true,
    },
    {
      id: 'gradient-overlay',
      type: 'rect',
      x: 0,
      y: 1200,
      width: 1080,
      height: 720,
      fill: '#000000',
      opacity: 0.6,
    },
    {
      id: 'headline',
      type: 'text',
      x: 60,
      y: 1380,
      width: 960,
      height: 180,
      text: 'New Arrival',
      fontSize: 72,
      fontFamily: 'Montserrat',
      fontStyle: 'bold',
      fill: '#ffffff',
      align: 'left',
      lineHeight: 1.15,
      role: 'headline',
    },
    {
      id: 'body',
      type: 'text',
      x: 60,
      y: 1570,
      width: 960,
      height: 80,
      text: 'The latest collection is here. Explore now.',
      fontSize: 26,
      fontFamily: 'Montserrat',
      fontStyle: 'normal',
      fill: '#d1d5db',
      align: 'left',
      lineHeight: 1.4,
      role: 'body',
    },
    {
      id: 'cta-bg',
      type: 'rect',
      x: 60,
      y: 1700,
      width: 280,
      height: 64,
      fill: '#10b981',
      cornerRadius: 32,
      colorRole: 'accent',
    },
    {
      id: 'cta-text',
      type: 'text',
      x: 60,
      y: 1700,
      width: 280,
      height: 64,
      text: 'Shop Now',
      fontSize: 24,
      fontFamily: 'Montserrat',
      fontStyle: 'bold',
      fill: '#ffffff',
      align: 'center',
      padding: 18,
      role: 'cta',
    },
  ],
};
