import type { TemplateDefinition } from './types';

export const storyBold: TemplateDefinition = {
  id: 'story-bold',
  name: 'Bold Promo',
  category: 'promo',
  thumbnail: '/templates/story-bold-thumb.png',
  width: 1080,
  height: 1920,
  format: 'story',
  defaults: {
    primaryColor: '#f43f5e',
    secondaryColor: '#ffffff',
    accentColor: '#fbbf24',
    fontFamily: 'Bebas Neue',
  },
  layers: [
    {
      id: 'bg-rect',
      type: 'rect',
      x: 0,
      y: 0,
      width: 1080,
      height: 1920,
      fill: '#fbbf24',
      colorRole: 'accent',
    },
    {
      id: 'headline',
      type: 'text',
      x: 60,
      y: 320,
      width: 960,
      height: 300,
      text: 'MEGA\nSALE',
      fontSize: 140,
      fontFamily: 'Bebas Neue',
      fontStyle: 'normal',
      fill: '#f43f5e',
      align: 'center',
      lineHeight: 1.0,
      role: 'headline',
      colorRole: 'primary',
    },
    {
      id: 'body',
      type: 'text',
      x: 120,
      y: 660,
      width: 840,
      height: 80,
      text: 'Up to 70% off everything this weekend only.',
      fontSize: 28,
      fontFamily: 'Bebas Neue',
      fontStyle: 'normal',
      fill: '#1c1917',
      align: 'center',
      lineHeight: 1.3,
      role: 'body',
    },
    {
      id: 'product-image',
      type: 'image',
      x: 340,
      y: 800,
      width: 400,
      height: 400,
      src: '',
      editable: true,
    },
    {
      id: 'cta-bg',
      type: 'rect',
      x: 240,
      y: 1340,
      width: 600,
      height: 80,
      fill: '#f43f5e',
      cornerRadius: 40,
      colorRole: 'primary',
    },
    {
      id: 'cta-text',
      type: 'text',
      x: 240,
      y: 1340,
      width: 600,
      height: 80,
      text: 'SHOP THE SALE',
      fontSize: 32,
      fontFamily: 'Bebas Neue',
      fontStyle: 'normal',
      fill: '#ffffff',
      align: 'center',
      padding: 22,
      role: 'cta',
    },
  ],
};
